security:
    encoders:
        App\Security\AuthUser:
            algorithm: bcrypt
            cost: 12
    providers:
        db_provider:
            id: App\Security\UserProvider
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            user_checker: App\Security\UserChecker
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
                use_referer: true
                require_previous_session: false
                default_target_path: index
            logout:
                path:   /logout
                target: /login
            access_denied_handler: App\Security\AccessDeniedHandler
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users, roles: ROLE_ADMIN }
        - { path: ^/$, roles: IS_AUTHENTICATED_FULLY }
