version: '2'

services:
    mariadb:
      container_name: sim_mariadb
      image: mariadb:latest
      volumes:
        - ./docker/mariadb/data:/var/lib/mysql
      env_file:
        - ./docker/env
      ports:
        - "3306:3306"

    php:
      build: ./docker/php-fpm
      container_name: sim_php
      ports:
        - "8080:8080" # for webpack-encore-server assets
      volumes:
        - .:/var/www
      env_file:
        - ./docker/env

    nginx:
      build: ./docker/nginx
      container_name: sim_nginx
      ports: 
        - "80:80"
      env_file:
        - ./docker/env
      volumes_from:
        - php
