parameters:
    locale: 'en'
    mail.default_from: 'draftee@gmail.com'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


## REPOSITORY
    App\Doctrine\Repository\UserRepository:
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - App\Entity\User

    App\Repository\UserRepositoryInterface:
        alias: App\Doctrine\Repository\UserRepository

    App\Doctrine\Repository\PasswordRepository:
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - App\Entity\Password

    App\Repository\PasswordRepositoryInterface:
        alias: App\Doctrine\Repository\PasswordRepository

    App\Doctrine\Repository\PasswordKeyRepository:
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - App\Entity\PasswordKey

    App\Repository\PasswordKeyRepositoryInterface:
        alias: App\Doctrine\Repository\PasswordKeyRepository

## SECURITY
    App\Security\UserProvider:
        arguments:
            $userRepository: '@App\Repository\UserRepositoryInterface'

    App\Security\AccessDeniedHandler:
        arguments:
            $router: '@router'

    App\Security\LoggedInUserProvider:
        arguments:
            $tokenStorage: '@security.token_storage'


## APPLICATION SERVICES
    App\Service\UserService:
        arguments:
            $userRepository: '@App\Repository\UserRepositoryInterface'

    App\Service\SecurityService:
        arguments:
            $userRepository: '@App\Repository\UserRepositoryInterface'
            $mailSender: '@App\Mail\MailSender'

    App\Service\Passwordservice:
        arguments:
            $passwordKeyRepository: '@App\Repository\PasswordKeyRepositoryInterface'
            $loggedInUserProvider: '@App\Security\LoggedInUserProvider'
            $userRepository: '@App\Repository\UserRepositoryInterface'


## MAIL
    App\Mail\MailSender:
        arguments:
            $mailer: '@mailer'
            $templating: '@twig'
            $defaultFrom: '%mail.default_from%'
            $router: '@router'
